API Fixes, README cleanup, and generated Reference Documentation
nearprotocol/assemblyscript-json pull request #121
Opened 2021-02-06 02:03 UTC by torch2424

Yo! :wave: 

So firstly, my apologies for the large PR :upside_down_face: 

*What had happened was*, my plan was to just update the README, but, when I tried using the API the way the README laid it out. It didn't work. And what I assumed happened was that the README must have gotten super out of date with the actual implementation, and thus no longer worked. So I ended up just cleaning up the `JSON` namespace. And API. And since the PR was already huge by then, I was like eh, the last thing I wanted to do was add reference docs using Typedoc, so, let's just do it in this PR :upside_down_face: 

Anyways! What this PR does:

* Removes the JSON Namespace, and instead, uses the ES module nampespacing pattern (Which I actually fixed in the compiler :tada: :muscle: )
* Implements a `.valueOf` function on our JSON types, to get the underlying primitive type.
* Implements the `getX` functions on the JSON.Obj.
* Impelements the `.isX` on the parent `JSON.Value` class.
* Cleans up the README and fixes up all the API info
* Creates a test to make sure the Usage in the README works.
* Installs Typedoc to generate reference API documentation
* Adds some scripts to generate and "deploy" docs so that they match the latest code
* Adds generating docs to the Travis (It's super helpful for catching bugs! :smile: )

And to mak the review a lot easier, I'd highly suggest just ignoring everything in `docs/` as that is all generated :smile: 

Let me know what you think! Thanks! cc @willemneal 

![Screenshot from 2021-02-05 17-58-05](https://user-images.githubusercontent.com/1448289/107105532-bbba9c80-67db-11eb-8aa5-878cf0f03923.png)
![Screenshot from 2021-02-05 17-57-55](https://user-images.githubusercontent.com/1448289/107105534-bc533300-67db-11eb-9d6b-37749b8f1b76.png)

2021-02-08 18:08 UTC, willemneal commented on assembly/JSON.ts
> +          '"' + this.keys[i] + '":' + this._obj.get(this.keys[i]).toString()
Do you have any tests for this?  Given the error above in value's `toString` it seems like since the value isn't cast to the subclass it should fail.

2021-02-08 18:10 UTC, willemneal requested changes
Thanks this looks great!  My one request is a simple test for `toString` for each class.

2021-02-09 23:05 UTC, torch2424 commented
@willemneal Made your requested changes! This should now be good to go! :smile: :tada:

2021-02-10 14:53 UTC, willemneal approved these changes
Thanks!  LGTM!

2021-02-10 15:09 UTC, merged